SELECT TOP (1000) [PROPERTY_ID]
      ,[COUNTRY]
      ,[PROVINCE]
      ,[City]
      ,[PROPERTY_PRICE]
      ,[BATHROOMS]
      ,[PARKING]
      ,[BEDROOMS]
      ,[Monthly_Repayment]
      ,[FLOOR_SIZE]
      ,[Min_Gross_Monthly_Income]
      ,[Total_Once_off_Costs]
  FROM [property28].[dbo].[property_places]
